/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUserRouteImport } from './routes/api/user'
import { Route as ApiStoryMediaSplatRouteImport } from './routes/api/story-media/$'
import { Route as ApiMediaUploadRouteImport } from './routes/api/media/upload'
import { Route as ApiStoriesIdFinalizeRouteImport } from './routes/api/stories/$id/finalize'
import { Route as ApiStoriesIdAssembleRouteImport } from './routes/api/stories/$id/assemble'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserRoute = ApiUserRouteImport.update({
  id: '/api/user',
  path: '/api/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoryMediaSplatRoute = ApiStoryMediaSplatRouteImport.update({
  id: '/api/story-media/$',
  path: '/api/story-media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaUploadRoute = ApiMediaUploadRouteImport.update({
  id: '/api/media/upload',
  path: '/api/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesIdFinalizeRoute = ApiStoriesIdFinalizeRouteImport.update({
  id: '/api/stories/$id/finalize',
  path: '/api/stories/$id/finalize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesIdAssembleRoute = ApiStoriesIdAssembleRouteImport.update({
  id: '/api/stories/$id/assemble',
  path: '/api/stories/$id/assemble',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/user': typeof ApiUserRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/story-media/$': typeof ApiStoryMediaSplatRoute
  '/api/stories/$id/assemble': typeof ApiStoriesIdAssembleRoute
  '/api/stories/$id/finalize': typeof ApiStoriesIdFinalizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/user': typeof ApiUserRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/story-media/$': typeof ApiStoryMediaSplatRoute
  '/api/stories/$id/assemble': typeof ApiStoriesIdAssembleRoute
  '/api/stories/$id/finalize': typeof ApiStoriesIdFinalizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/user': typeof ApiUserRoute
  '/api/media/upload': typeof ApiMediaUploadRoute
  '/api/story-media/$': typeof ApiStoryMediaSplatRoute
  '/api/stories/$id/assemble': typeof ApiStoriesIdAssembleRoute
  '/api/stories/$id/finalize': typeof ApiStoriesIdFinalizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/user'
    | '/api/media/upload'
    | '/api/story-media/$'
    | '/api/stories/$id/assemble'
    | '/api/stories/$id/finalize'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/user'
    | '/api/media/upload'
    | '/api/story-media/$'
    | '/api/stories/$id/assemble'
    | '/api/stories/$id/finalize'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/user'
    | '/api/media/upload'
    | '/api/story-media/$'
    | '/api/stories/$id/assemble'
    | '/api/stories/$id/finalize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiUserRoute: typeof ApiUserRoute
  ApiMediaUploadRoute: typeof ApiMediaUploadRoute
  ApiStoryMediaSplatRoute: typeof ApiStoryMediaSplatRoute
  ApiStoriesIdAssembleRoute: typeof ApiStoriesIdAssembleRoute
  ApiStoriesIdFinalizeRoute: typeof ApiStoriesIdFinalizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user': {
      id: '/api/user'
      path: '/api/user'
      fullPath: '/api/user'
      preLoaderRoute: typeof ApiUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/story-media/$': {
      id: '/api/story-media/$'
      path: '/api/story-media/$'
      fullPath: '/api/story-media/$'
      preLoaderRoute: typeof ApiStoryMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/upload': {
      id: '/api/media/upload'
      path: '/api/media/upload'
      fullPath: '/api/media/upload'
      preLoaderRoute: typeof ApiMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories/$id/finalize': {
      id: '/api/stories/$id/finalize'
      path: '/api/stories/$id/finalize'
      fullPath: '/api/stories/$id/finalize'
      preLoaderRoute: typeof ApiStoriesIdFinalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories/$id/assemble': {
      id: '/api/stories/$id/assemble'
      path: '/api/stories/$id/assemble'
      fullPath: '/api/stories/$id/assemble'
      preLoaderRoute: typeof ApiStoriesIdAssembleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiUserRoute: ApiUserRoute,
  ApiMediaUploadRoute: ApiMediaUploadRoute,
  ApiStoryMediaSplatRoute: ApiStoryMediaSplatRoute,
  ApiStoriesIdAssembleRoute: ApiStoriesIdAssembleRoute,
  ApiStoriesIdFinalizeRoute: ApiStoriesIdFinalizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
